//{{NO_DEPENDENCIES}}
// Von Microsoft Visual C++ generierte Includedatei.
// Verwendet durch MaX.rc
//
#define IDC_OGL_READ                    2
#define IDC_WIN_DEFAULTS                3
#define IDC_FUN_DEFAULT                 3
#define IDC_ClearField                  3
#define IDC_FFIELD_CHECK                3
#define IDC_READ_GRF                    3
#define IDC_BND_INSPOLY                 3
#define IDC_EXP_WRITE                   3
#define IDC_PRO_WRITE                   3
#define IDC_INT_READ                    3
#define IDC_OBJECT_LOCATION             3
#define IDC_SPACE_XAXIS                 3
#define IDC_OGL_WRITE                   3
#define IDC_MOVIE_CHECK                 3
#define IDC_GetMinMax                   4
#define IDC_MOVIE_GENERATE              4
#define IDC_WRITE_GRF                   4
#define IDC_BND_INSPOLYE                4
#define IDC_EXP_INSEXP                  4
#define IDC_WIN_READ                    4
#define IDC_PRO_READ                    4
#define IDC_FUN_READ                    4
#define IDC_INT_WRITE                   4
#define IDC_SPACE_YAXIS                 4
#define IDC_OBJECT_AXIS                 4
#define IDC_OGL_DEFAULT                 4
#define IDC_CFLD_SPACE                  5
#define IDC_WRITE_FLF                   5
#define IDC_BND_DELPOLY                 5
#define IDC_MOVIE_PERFORM               5
#define IDC_EXP_DELEXP                  5
#define IDC_WIN_WRITE                   5
#define IDC_FGRID_CHECK                 5
#define IDC_FUN_WRITE                   5
#define IDC_OBJECT_ADD                  5
#define IDC_SPACE_ZAXIS                 5
#define IDC_OGL_TUBE                    5
#define IDC_VIEW_PLANE                  6
#define IDC_MOVIE_READ                  6
#define IDC_BND_DELPOLYE                6
#define IDC_EXP_READ                    6
#define IDC_FUN_DELETE                  6
#define IDC_OBJECT_DELETE               6
#define IDC_WIN_READ_PAL                6
#define IDC_GridFormula                 7
#define IDC_MOVIE_WRITE                 7
#define IDC_BND_MODPOLYE                7
#define IDC_READ_FLF                    7
#define IDC_EXP_DRAW                    7
#define IDC_OBJECT_COPY                 7
#define IDC_WIN_SET_TITLE               7
#define IDC_FieldFormula                8
#define IDC_BND_MODPOLY                 8
#define IDC_EXP_LOC                     8
#define IDC_FFIELD_ACCEPT               8
#define IDC_MOVIE_PERFORM2              8
#define IDC_OBJECT_READ                 8
#define IDC_TransformGrid               9
#define IDC_BND_WRITE                   9
#define IDC_EXP_COPEXP                  9
#define IDC_MOVIE_CHECK2                9
#define IDC_OBJECT_WRITE                9
#define IDC_BND_ROTPOLY                 10
#define IDC_ClearDomain                 10
#define IDC_EXP_GENEXP                  10
#define IDC_OBJECT_Points               10
#define IDC_MOVIE_PERFORM3              10
#define IDC_BND_MOVPOLY                 11
#define IDC_EXP_AXIS                    11
#define IDC_OBJECT_Points3              11
#define IDC_ClearField2                 11
#define IDC_MOVIE_CHECK3                11
#define IDC_BND_BLOPOLY                 12
#define IDC_DomData                     12
#define IDC_EXP_GETDEPEND               12
#define IDC_MOVIE_PERFORM4              12
#define IDC_OBJECT_ORIGIN               12
#define IDC_BND_READ                    13
#define IDC_EXP_ALL0                    13
#define IDC_MOVIE_CHECK4                13
#define IDC_GetError                    14
#define IDC_BND_DRAW                    14
#define IDC_EXP_ALL1                    14
#define IDC_MOVIE_PERFORM5              14
#define IDC_CFLD_READ                   15
#define IDC_BND_CHECK                   15
#define IDC_EXP_GENEXPO                 15
#define IDC_MOVIE_CHECK5                15
#define IDC_CFLD_WRITE                  16
#define IDC_BND_MAS                     16
#define IDC_EXP_DELDEPEND               16
#define IDC_MOVIE_PERFORM6              16
#define IDC_EXP_MODEXP                  17
#define IDC_MOVIE_CHECK6                17
#define IDC_BND_GEO                     17
#define IDD_WINDOW                      103
#define IDD_FUNCTION                    106
#define IDB_BITMAP1                     107
#define IDB_BITMAP2                     108
#define IDB_BITMAP3                     109
#define IDB_BITMAP4                     110
#define IDB_BITMAP5                     111
#define IDB_BITMAP6                     112
#define IDD_ACTION                      130
#define IDD_OUTPUT                      131
#define IDD_MOUSE                       134
#define IDD_FIELD                       150
#define IDD_DOMAIN                      151
#define IDD_SPACE                       152
#define IDD_MFIELD                      153
#define IDD_FGRID                       154
#define IDD_FFIELD                      156
#define IDD_TGRID                       158
#define IDD_MOVIE                       164
#define IDI_ICON1                       203
#define IDI_ICON2                       204
#define IDI_ICON3                       205
#define IDI_ICON4                       206
#define IDI_ICON5                       207
#define IDI_ICON12                      208
#define IDI_ICON11                      209
#define IDI_ICON8                       210
#define IDI_ICON9                       211
#define IDD_BOUNDARY                    216
#define IDI_ICON6                       218
#define IDI_ICON7                       219
#define IDD_INTEGRAL                    220
#define IDD_EXPANSION                   221
#define IDD_PROJECT                     224
#define IDD_MMP                         225
#define IDD_TRANS                       226
#define IDI_ICON13                      230
#define IDI_ICON14                      231
#define IDI_ICON15                      232
#define IDI_ICON16                      233
#define IDI_ICON17                      234
#define IDI_ICON18                      235
#define IDI_ICON20                      237
#define IDI_ICON21                      238
#define IDD_PET                         239
#define IDD_INSERT                      240
#define IDD_OBJECT                      247
#define IDI_ICON22                      248
#define IDI_ICON23                      249
#define IDD_OGL                         250
#define IDD_EXPGEN2                     253
#define IDD_EXPGEN3                     254
#define IDD_MOBJECT                     255
#define IDD_POINTS2D                    256
#define IDD_POINTS3D                    257
#define IDD_EXPMOD2                     258
#define IDD_TUBE                        259
#define IDD_PFD                         260
#define IDD_GEO                         261
#define IDI_ICON10                      263
#define IDC_WIN_XMIN                    1004
#define IDC_WIN_XMAX                    1005
#define IDC_WIN_YMIN                    1006
#define IDC_WIN_YMAX                    1007
#define IDC_WIN_WIDTH                   1030
#define IDC_WIN_HEIGHT                  1031
#define IDC_WIN_XLABEL                  1032
#define IDC_WIN_YLABEL                  1033
#define IDC_WIN_RIGHT                   1034
#define IDC_WIN_XLABEL_ON               1035
#define IDC_WIN_YLABEL_ON               1036
#define IDC_WIN_TITLE                   1037
#define IDC_WIN_XAXIS_ON                1040
#define IDC_WIN_YAXIS_ON                1041
#define IDC_WIN_XLOG                    1042
#define IDC_WIN_YLOG                    1043
#define IDC_WIN_KWIN                    1044
#define IDC_WIN_LEFT                    1045
#define IDC_WIN_BOTTOM                  1046
#define IDC_WIN_TOP                     1047
#define IDC_FUN_M                       1049
#define IDC_FUN_MA                      1050
#define IDC_FUN_A1                      1051
#define IDC_FUN_A2                      1052
#define IDC_FUN_XMIN                    1053
#define IDC_FUN_ATITLE1                 1054
#define IDC_FUN_ATITLE2                 1055
#define IDC_FUN_MARK_Q                  1056
#define IDC_FUN_MARK_P                  1057
#define IDC_FUN_MARK_X                  1058
#define IDC_FUN_STYLE_P                 1059
#define IDC_FUN_STYLE_L                 1060
#define IDC_FUN_STYLE_D                 1061
#define IDC_FUN_MARK_SIZE               1062
#define IDC_FUN_MARK_STEP               1063
#define IDC_WIN_XGRID_ON                1063
#define IDC_FUN_MARK_COLOR              1064
#define IDC_WIN_XGRID                   1064
#define IDC_FUN_STYLE_WIDTH             1065
#define IDC_FUN_STYLE_STEP              1066
#define IDC_WIN_YGRID_ON                1066
#define IDC_FUN_STYLE_COLOR             1067
#define IDC_WIN_YGRID                   1068
#define IDC_FUN_XMAX                    1068
#define IDC_WIN_PAL_GRAY                1069
#define IDC_FUN_YMIN                    1069
#define IDC_WIN_PAL_COLOR               1070
#define IDC_FUN_YMAX                    1070
#define IDC_WIN_PAL_VARIABLE            1071
#define IDC_FUN_A3                      1071
#define IDC_WIN_CGRID                   1072
#define IDC_FUN_A4                      1072
#define IDC_WIN_FIE                     1073
#define IDC_FUN_POLAR                   1073
#define IDC_WIN_FUN                     1074
#define IDC_FUN_POLAR_DB                1074
#define IDC_FUN_POLAR_2                 1075
#define IDC_FUN_OFFSET                  1076
#define IDC_FUN_SCALE                   1077
#define IDC_FUN_RMIN2                   1078
#define IDC_FUN_RMAX2                   1079
#define IDC_FUN_POLAR_CLIP              1080
#define IDC_FUN_1                       1081
#define IDC_FUN_2                       1082
#define IDC_FUN_A1S                     1122
#define IDC_FUN_A2S                     1123
#define IDC_FUN_STYLE_WIDTHS            1124
#define IDC_FUN_STYLE_STEPS             1125
#define IDC_FUN_STYLE_COLORS            1126
#define IDC_FUN_MARK_COLORS             1127
#define IDC_FUN_MARK_STEPS              1128
#define IDC_FUN_MARK_SIZES              1129
#define IDC_ACTION_STOP                 1152
#define IDC_ACTION_COMPUTE_FUN          1153
#define IDC_ACTION_DRAW_FUN             1154
#define IDC_MOUSE_ID                    1154
#define IDC_MOUSE_X                     1155
#define IDC_MOUSE_Y                     1156
#define IDC_ACTION_DRAW_FLD             1156
#define IDC_MOUSE_XT                    1157
#define IDC_ACTION_COMPUTE_FLD          1157
#define IDC_MOUSE_YT                    1158
#define IDC_OUT_M1                      1158
#define IDC_ACTION_CLEAR                1159
#define IDC_MOUSE_VX                    1159
#define IDC_OUT_N1                      1159
#define IDC_LXRFLD                      1160
#define IDC_MOUSE_VY                    1160
#define IDC_ACTION_GENERATE_MOVIE       1160
#define IDC_OUT_TEXT1                   1160
#define IDC_LYRFLD                      1161
#define IDC_MOUSE_VZ                    1161
#define IDC_ACTION_WINDOW_OPTIONS       1161
#define IDC_OUT_M2                      1161
#define IDC_LZRFLD                      1162
#define IDC_MOUSE_VXT                   1162
#define IDC_ACTION_MOVIE_SCRIPT         1162
#define IDC_OUT_N2                      1162
#define IDC_LARFLD                      1163
#define IDC_MOUSE_VYT                   1163
#define IDC_OUT_TEXT2                   1163
#define IDC_ACTION_COMPUTE_BND          1163
#define IDC_LITE                        1164
#define IDC_MOUSE_VZT                   1164
#define IDC_OUT_M3                      1164
#define IDC_ACTION_DRAW_BND             1164
#define IDC_LITH                        1165
#define IDC_MOUSE_ZT                    1165
#define IDC_OUT_N3                      1165
#define IDC_ACTION_DRAW_EXP             1165
#define IDC_LITS                        1166
#define IDC_MOUSE_Z                     1166
#define IDC_OUT_TEXT4                   1166
#define IDC_ACTION_COMPUTE_EXP          1166
#define IDC_LITD                        1167
#define IDC_OUT_TEXT3                   1167
#define IDC_ACTION_COMPUTE_MMP          1167
#define IDC_LITB                        1168
#define IDC_MOUSE_J                     1168
#define IDC_ACTION_COMPUTE_GFD          1168
#define IDC_LITJ                        1169
#define IDC_MOUSE_I                     1169
#define IDC_ACTION_OGL_WINDOW_OPTIONS   1169
#define IDC_LITA                        1170
#define IDC_ACTION_COMPUTE_PRO          1170
#define IDC_MOUSE_VA                    1170
#define IDC_LITWE                       1171
#define IDC_ACTION_COMPUTE_INT          1171
#define IDC_MOUSE_VAT                   1171
#define IDC_LITWH                       1172
#define IDC_ACTION_DRAW_DOM             1172
#define IDC_LITWT                       1173
#define IDC_ACTION_COMPUTE_DOM          1173
#define IDC_LITPE                       1174
#define IDC_ACTION_DRAW_OBJ             1174
#define IDC_LITPH                       1175
#define IDC_ACTION_COMPUTE_OBJ          1175
#define IDC_LITPT                       1176
#define IDC_LXCFLD                      1177
#define IDC_LYCFLD                      1178
#define IDC_LPRFLD                      1179
#define IDC_NXCFLD                      1180
#define IDC_NDOM                        1182
#define IDC_LXYPLANE                    1182
#define IDC_KDOM                        1183
#define IDC_NSFLD                       1183
#define IDC_ITARROW                     1184
#define IDC_EDOM                        1184
#define IDC_LITV                        1185
#define IDC_MINCARROW                   1186
#define IDC_SDOM                        1186
#define IDC_MAXCARROW                   1187
#define IDC_TDOM                        1187
#define IDC_ITINTENSITY                 1188
#define IDC_UDOM                        1188
#define IDC_MINCINTENSITY               1189
#define IDC_ADD_DOM                     1190
#define IDC_MAXCINTENSITY               1190
#define IDC_DEL_DOM                     1191
#define IDC_RISOSTEP                    1191
#define IDC_LZCFLD                      1192
#define IDC_ADJ_DOM                     1192
#define IDC_GRID3D                      1193
#define IDC_CHK_DOM                     1193
#define IDC_LECFLD                      1194
#define IDC_KDOMS                       1194
#define IDC_LHCFLD                      1195
#define IDC_SPACE_TEXT                  1195
#define IDC_LACFLD                      1196
#define IDC_SPACE_X0                    1196
#define IDC_KDOMCOLOR                   1196
#define IDC_LVCFLD                      1197
#define IDC_SPACE_Y0                    1197
#define IDC_MFIELD_EXR                  1197
#define IDC_DRAW_DOM                    1197
#define IDC_SPACE_Z0                    1198
#define IDC_MFIELD_EYR                  1198
#define IDC_FGRID_X                     1198
#define IDC_NYCFLD                      1199
#define IDC_SPACE_X1                    1199
#define IDC_MFIELD_EZR                  1199
#define IDC_FGRID_Y                     1199
#define IDC_NZCFLD                      1200
#define IDC_SPACE_Y1                    1200
#define IDC_MFIELD_HXR                  1200
#define IDC_FGRID_Z                     1200
#define IDC_SPACE_Z1                    1201
#define IDC_LGRID3D                     1201
#define IDC_MFIELD_HYR                  1201
#define IDC_FFIELD_E                    1201
#define IDC_SPACE_X2                    1202
#define IDC_LEVPLANE                    1202
#define IDC_MFIELD_HZR                  1202
#define IDC_FFIELD_H                    1202
#define IDC_SPACE_Y2                    1203
#define IDC_MFIELD_AXR                  1203
#define IDC_FFIELD_A                    1203
#define IDC_SPACE_Z2                    1204
#define IDC_LISOLINE                    1204
#define IDC_MFIELD_AYR                  1204
#define IDC_FFIELD_V                    1204
#define IDC_SPACE_X3                    1205
#define IDC_MFIELD_AZR                  1205
#define IDC_FFIELD_X                    1205
#define IDC_SPACE_Y3                    1206
#define IDC_LISOFILL                    1206
#define IDC_MFIELD_VR                   1206
#define IDC_FFIELD_Y                    1206
#define IDC_RMINFLD                     1207
#define IDC_SPACE_Z3                    1207
#define IDC_MFIELD_EXI                  1207
#define IDC_FFIELD_Z                    1207
#define IDC_RMAXFLD                     1208
#define IDC_MFIELD_EYI                  1208
#define IDC_CONFORM_CHECK               1208
#define IDC_SPACE_ANGLE                 1208
#define IDC_TRFLD                       1209
#define IDC_MFIELD_EZI                  1209
#define IDC_CONFORM_F                   1209
#define IDC_LARROWFILL                  1210
#define IDC_MFIELD_HXI                  1210
#define IDC_CONFORM_P0R                 1210
#define IDC_LRGRD                       1211
#define IDC_MFIELD_HYI                  1211
#define IDC_CONFORM_P0I                 1211
#define IDC_LXZPLANE                    1212
#define IDC_MFIELD_HZI                  1212
#define IDC_CONFORM_APPLY               1212
#define IDC_LYZPLANE                    1213
#define IDC_MFIELD_AXI                  1213
#define IDC_CONFORM_P1R                 1213
#define IDC_VIEWDIST                    1214
#define IDC_MFIELD_AYI                  1214
#define IDC_CONFORM_P1I                 1214
#define IDC_READ_DOM                    1214
#define IDC_SCALEARROW                  1215
#define IDC_MFIELD_AZI                  1215
#define IDC_CONFORM_P2R                 1215
#define IDC_WRITE_DOM                   1215
#define IDC_ARROWLENGTH                 1216
#define IDC_MFIELD_VI                   1216
#define IDC_CONFORM_P2I                 1216
#define IDC_SCALEINTENSITY              1217
#define IDC_MFIELD_X                    1217
#define IDC_CONFORM_P3R                 1217
#define IDC_MFIELD_Y                    1218
#define IDC_CONFORM_P3I                 1218
#define IDC_TPRFLD                      1218
#define IDC_MFIELD_Z                    1219
#define IDC_TRANSFORM_X                 1219
#define IDC_TRANSFORM_CHECK             1220
#define IDC_TRANSFORM_P0                1221
#define IDC_RSUMFLD                     1221
#define IDC_RSUM2FLD                    1222
#define IDC_TRANSFORM_APPLY             1223
#define IDC_ERRFLD                      1223
#define IDC_TRANSFORM_P1                1224
#define IDC_ERR2FLD                     1224
#define IDC_READ_GRT                    1225
#define IDC_TRANSFORM_P2                1226
#define IDC_FFIELD_IQ                   1226
#define IDC_MFIELD_NX                   1227
#define IDC_FFIELD_Q                    1227
#define IDC_WRITE_GRT                   1227
#define IDC_MFIELD_NY                   1228
#define IDC_TRANSFORM_P3                1228
#define IDC_FFIELD_KEXP                 1228
#define IDC_MFIELD_NZ                   1229
#define IDC_FFIELD_KCOL                 1229
#define IDC_MFIELD_IDOM                 1230
#define IDC_TRANSFORM_Y                 1230
#define IDC_FField_IQS                  1230
#define IDC_TRANSFORM_Z                 1231
#define IDC_CFORM6                      1231
#define IDC_MFIELD_NX2                  1231
#define IDC_CFORM7                      1232
#define IDC_MFIELD_NY2                  1232
#define IDC_CFORM8                      1233
#define IDC_MFIELD_NZ2                  1233
#define IDC_FField_LIQ                  1234
#define IDC_FField_LEXP                 1235
#define IDC_MOVIE_NPIC                  1236
#define IDC_FFIELD_KDOM                 1236
#define IDC_FFIELD_KPAR                 1237
#define IDC_MOVIE_KCOMMAND              1238
#define IDC_FFIELD_KCON                 1238
#define IDC_MOVIE_KCOMMANDS             1239
#define IDC_FField_LEXC                 1239
#define IDC_MOVIE_NSEQ                  1240
#define IDC_MOVIE_DELAY                 1244
#define IDC_BND_R                       1245
#define IDC_BND_KBND                    1246
#define IDC_BND_KEDGE                   1247
#define IDC_BND_Y                       1248
#define IDC_BND_X                       1249
#define IDC_BND_XA                      1250
#define IDC_BND_XB                      1251
#define IDC_BND_YA                      1252
#define IDC_BND_YB                      1253
#define IDC_BND_KBNDS                   1254
#define IDC_BND_KEDGES                  1255
#define IDC_BND_NEDGE                   1256
#define IDC_BND_KVALS                   1257
#define IDC_BND_NBND                    1258
#define IDC_BND_XO                      1259
#define IDC_BND_YO                      1260
#define IDC_BND_COLOR                   1261
#define IDC_BND_COLORS                  1262
#define IDC_BND_KVAL                    1263
#define IDC_BND_LDOM                    1264
#define IDC_BND_LDOMS                   1265
#define IDC_BND_W                       1266
#define IDC_BND_RDOM                    1267
#define IDC_BND_RDOMS                   1268
#define IDC_BND_D                       1269
#define IDC_BND_CLOSED                  1270
#define IDC_INT_LDOM                    1271
#define IDC_INT_RDOM                    1272
#define IDC_INT_NBND                    1273
#define IDC_BND_VAL                     1273
#define IDC_INT_KBND                    1274
#define IDC_INT_KBNDS                   1275
#define IDC_BND_WEIGHT                  1275
#define IDC_INT_BNDINT                  1276
#define IDC_BND_CONN                    1276
#define IDC_INT_XMIN                    1277
#define IDC_BND_FORM                    1277
#define IDC_INT_XMAX                    1278
#define IDC_BND_AMP                     1278
#define IDC_INT_YMIN                    1279
#define IDC_BND_PTS                     1279
#define IDC_INT_YMAX                    1280
#define IDC_BND_MATPTS                  1280
#define IDC_INT_NX                      1281
#define IDC_INT_NY                      1282
#define IDC_INT_RECINT                  1283
#define IDC_INT_FX                      1284
#define IDC_INT_FY                      1285
#define IDC_INT_FZ                      1286
#define IDC_INT_FDL                     1287
#define IDC_MOVIE_COMMAND               1287
#define IDC_INT_FDN                     1288
#define IDC_MOVIE_COMMAND2              1288
#define IDC_INT_SUM                     1289
#define IDC_EXP_KEXP                    1289
#define IDC_MOVIE_COMMAND3              1289
#define IDC_INT_GL                      1290
#define IDC_EXP_KEXPS                   1290
#define IDC_MOVIE_COMMAND4              1290
#define IDC_INT_GK                      1291
#define IDC_EXP_NEXP                    1291
#define IDC_MOVIE_COMMAND5              1291
#define IDC_INT_HP                      1292
#define IDC_EXP_ICOL                    1292
#define IDC_PRO_LFCFLD                  1292
#define IDC_MOVIE_COMMAND6              1292
#define IDC_INT_ITER                    1293
#define IDC_EXP_ICOLS                   1293
#define IDC_PRO_FRFLD                   1293
#define IDC_INT_IORD                    1294
#define IDC_EXP_IDOM                    1294
#define IDC_PRO_FIFLD                   1294
#define IDC_INT_ACC                     1295
#define IDC_EXP_IDOMS                   1295
#define IDC_PRO_LGCFLD                  1295
#define IDC_INT_INTER0                  1296
#define IDC_PRO_GRFLD                   1296
#define IDC_EXP_ICONN                   1296
#define IDC_INT_INTER1                  1297
#define IDC_PRO_GIFLD                   1297
#define IDC_EXP_ICONNS                  1297
#define IDC_INT_INTER2                  1298
#define IDC_EXP_NPAR                    1298
#define IDC_INT_INTER3                  1299
#define IDC_EXP_KPAR                    1299
#define IDC_PRO_XPERIOD                 1299
#define IDC_INT_RESULT                  1300
#define IDC_EXP_KPARS                   1300
#define IDC_PRO_LGEIGEN                 1300
#define IDC_INT_IERR                    1301
#define IDC_EXP_PAR1                    1301
#define IDC_PRO_LEIGEN                  1301
#define IDC_INT_ICALL                   1302
#define IDC_EXP_PAR2                    1302
#define IDC_PRO_C1REIGEN                1302
#define IDC_PRO_C1IEIGEN                1303
#define IDC_EXP_SIEXPS                  1303
#define IDC_INT_FIELD0                  1303
#define IDC_PRO_C2REIGEN                1304
#define IDC_EXP_SREXPS                  1304
#define IDC_INT_FIELDE                  1304
#define IDC_PRO_C2IEIGEN                1305
#define IDC_EXP_AMP                     1305
#define IDC_INT_FIELDH                  1305
#define IDC_PRO_IXYSYMMS                1306
#define IDC_EXP_IPAR                    1306
#define IDC_INT_FIELDS                  1306
#define IDC_PRO_LFEIGEN                 1307
#define IDC_EXP_LPLW                    1307
#define IDC_INT_RESULTMAX               1307
#define IDC_PRO_NIEIGEN                 1308
#define IDC_EXP_L2DPOL                  1308
#define IDC_INT_RESULTMIN               1308
#define IDC_PRO_NREIGEN                 1309
#define IDC_EXP_L2DBESSEL               1309
#define IDC_INT_RESULTMINX              1309
#define IDC_PRO_IXYSYMM                 1310
#define IDC_EXP_LE                      1310
#define IDC_INT_RESULTMAXX              1310
#define IDC_PRO_IXZSYMM                 1311
#define IDC_EXP_LH                      1311
#define IDC_INT_RESULTMINY              1311
#define IDC_PRO_IYZSYMM                 1312
#define IDC_EXP_LHE                     1312
#define IDC_INT_RESULTMINZ              1312
#define IDC_PRO_IXZSYMMS                1313
#define IDC_EXP_LCONN                   1313
#define IDC_INT_RESULTMAXY              1313
#define IDC_PRO_IYZSYMMS                1314
#define IDC_EXP_SIEXP                   1314
#define IDC_INT_RESULTMAXZ              1314
#define IDC_EXP_IEXP                    1315
#define IDC_PRO_ITMEIGEN                1315
#define IDC_INT_FIELDF                  1315
#define IDC_PRO_AEIGEN                  1316
#define IDC_EXP_SREXP                   1316
#define IDC_INT_Location                1316
#define IDC_PRO_FEIGEN                  1317
#define IDC_EXP_REXP                    1317
#define IDC_INT_R                       1317
#define IDC_PRO_IMEIGEN                 1318
#define IDC_EXP_LRAY                    1318
#define IDC_INT_1                       1318
#define IDC_PRO_LE                      1319
#define IDC_MMP_SOLVE                   1319
#define IDC_EXP_L2DHARMONIC             1319
#define IDC_PRO_LH                      1320
#define IDC_MMP_POINTS                  1320
#define IDC_EXP_ORIGY                   1320
#define IDC_PRO_LHE                     1321
#define IDC_MMP_READ                    1321
#define IDC_EXP_ORIGX                   1321
#define IDC_PRO_LXPERIOD                1322
#define IDC_MMP_WRITE                   1322
#define IDC_PET_WRITE                   1322
#define IDC_EXP_L3DBESSEL               1322
#define IDC_MMP_SOLVEE                  1323
#define IDC_PET_CHECK                   1323
#define IDC_EXP_LC                      1323
#define IDC_PRO_YPERIODX                1323
#define IDC_PRO_LYPERIOD                1324
#define IDC_MMP_RESIDUAL                1324
#define IDC_EXP_LS                      1324
#define IDC_PRO_CXRPERIOD               1325
#define IDC_MMP_ERROR                   1325
#define IDC_INT_KOBJ                    1325
#define IDC_EXP_LCS                     1325
#define IDC_PRO_CXIPERIOD               1326
#define IDC_MMP_ERRM                    1326
#define IDC_INT_KOBJS                   1326
#define IDC_EXP_KEXC                    1326
#define IDC_PRO_CYRPERIOD               1327
#define IDC_MMP_NBNDPT                  1327
#define IDC_TRANS_T1                    1327
#define IDC_INT_NOBJ                    1327
#define IDC_EXP_KEXCS                   1327
#define IDC_PRO_CYIPERIOD               1328
#define IDC_TRANS_R1                    1328
#define IDC_BND_LET                     1328
#define IDC_MMP_BNDDMAX                 1328
#define IDC_EXP_NEXC                    1328
#define IDC_MMP_nSegPt                  1329
#define IDC_TRANS_T2                    1329
#define IDC_BND_LEZ                     1329
#define IDC_PRO_LEIGENSAVE              1329
#define IDC_TRANS_R2                    1330
#define IDC_BND_LDN                     1330
#define IDC_MMP_ERRA                    1330
#define IDC_PRO_LZPER                   1330
#define IDC_INT_OBJINT                  1330
#define IDC_TRANS_T3                    1331
#define IDC_BND_LHT                     1331
#define IDC_MMP_itmCG                   1331
#define IDC_PRO_IWRITEDIGITS            1331
#define IDC_TRANS_R3                    1332
#define IDC_BND_LHZ                     1332
#define IDC_MMP_NPET                    1332
#define IDC_PRO_YPERIODY                1332
#define IDC_BND_LBN                     1333
#define IDC_MMP_itCG                    1333
#define IDC_PRO_CZRPERIOD               1333
#define IDC_BND_LUSUAL                  1334
#define IDC_MMP_itEigen                 1334
#define IDC_PRO_CZIPERIOD               1334
#define IDC_MMP_GUT                     1335
#define IDC_BND_LV                      1335
#define IDC_PRO_LZPERIOD                1335
#define IDC_MMP_GUR                     1336
#define IDC_BND_LAZ                     1336
#define IDC_PRO_ZPERIODX                1336
#define IDC_BND_LSPEC                   1337
#define IDC_MMP_CG                      1337
#define IDC_OUT_CHECK1                  1337
#define IDC_PRO_ZPERIODY                1337
#define IDC_BND_LYPER                   1338
#define IDC_MMP_IAMPL                   1338
#define IDC_OUT_CHECK2                  1338
#define IDC_INT_FIELD_AVER              1338
#define IDC_PRO_ZPERIODZ                1338
#define IDC_BND_LSIBC                   1339
#define IDC_MMP_PET                     1339
#define IDC_OUT_CHECK3                  1339
#define IDC_PRO_C1REIGEN2               1339
#define IDC_INT_FIELD_ABS               1339
#define IDC_BND_LXPER                   1340
#define IDC_MMP_INT1                    1340
#define IDC_OUT_CHECK4                  1340
#define IDC_PRO_C1IEIGEN2               1340
#define IDC_INT_FIELD_EB                1340
#define IDC_MMP_INTB                    1341
#define IDC_OUT_CHECK5                  1341
#define IDC_BND_LZPER                   1341
#define IDC_PRO_C2REIGEN2               1341
#define IDC_MMP_INTR                    1342
#define IDC_EXP_L3DPOL                  1342
#define IDC_PRO_C2IEIGEN2               1342
#define IDC_OUT_CHECK6                  1342
#define IDC_MMP_Amplitude               1343
#define IDC_EXP_L3DRING                 1343
#define IDC_PRO_LCEIGEN                 1343
#define IDC_OUT_CHECK7                  1343
#define IDC_MMP_BNDPPW                  1344
#define IDC_PRO_LRPERIOD                1344
#define IDC_MMP_BNDOVER                 1345
#define IDC_PRO_LEIGENSAVEFLD           1345
#define IDC_MMP_ROUGH                   1346
#define IDC_EXP_L3DLINE                 1346
#define IDC_PRO_MMEIGEN                 1346
#define IDC_MMP_FINE                    1347
#define IDC_EXP_IOBJ                    1347
#define IDC_PRO_IEIGEN                  1347
#define IDC_MMP_LPET                    1348
#define IDC_EXP_GAM1                    1348
#define IDC_PET_READ                    1349
#define IDC_MMP_CONN                    1349
#define IDC_EXP_GAM2                    1349
#define IDC_PET_SPET                    1350
#define IDC_MMP_WRITERR                 1350
#define IDC_EXPGEN3_GENF                1350
#define IDC_EXP_L3DSpiral               1350
#define IDC_PET_KPET                    1351
#define IDC_MMP_SCALERROR               1351
#define IDC_EXPGEN3_IGENOBJ             1351
#define IDC_PET_KPETS                   1352
#define IDC_MMP_MTRCOL                  1352
#define IDC_EXP_DEPEND                  1352
#define IDC_EXPGEN3_IGENINS             1352
#define IDC_MMP_MTRROW                  1353
#define IDC_EXP_DEPENDMAX               1353
#define IDC_EXPGEN3_IGENminE            1353
#define IDC_MMP_WRITEMTRX               1354
#define IDC_EXP_L3DGauss                1354
#define IDC_EXPGEN3_IGENmaxE            1354
#define IDC_INSERT_KOBJ                 1355
#define IDC_MMP_INTO                    1355
#define IDC_EXPGEN3_IGENmaxM            1355
#define idc_Exp_l2Dlayer                1355
#define IDC_INSERT_AFTER                1356
#define IDC_MMP_NBNDPT2                 1356
#define IDC_EXPGEN3_IGENCL              1356
#define idc_Exp_l3Dlayer                1356
#define IDC_MMP_IFUNW                   1357
#define IDC_EXPGEN3_IGENCN              1357
#define IDC_MMP_IFINDEXP                1358
#define IDC_EXPGEN3_IGENOB              1358
#define IDC_MMP_resCG                   1359
#define IDC_EXPGEN3_IGENCL2             1359
#define IDC_MMP_ISM                     1360
#define IDC_MMP_resPET                  1361
#define IDC_MMP_iaccCG                  1362
#define IDC_MMP_MATRIX0                 1363
#define IDC_MMP_Condition               1364
#define IDC_MMP_COND                    1365
#define IDC_MMP_L3F                     1366
#define IDC_MMP_CHO                     1367
#define IDC_MMP_QRR                     1368
#define IDC_MMP_INTP                    1369
#define IDC_MMP_iLast                   1370
#define IDC_OBJECT_KOBJ                 1383
#define IDC_OBJECT_KOBJS                1384
#define IDC_OBJECT_NOBJ                 1385
#define IDC_OBJECT_ICOL                 1386
#define IDC_OBJECT_TORUS                1387
#define IDC_OBJECT_CYLINDER             1388
#define IDC_OBJECT_IOBJ                 1389
#define IDC_OBJECT_SROBJS               1393
#define IDC_OBJECT_SROBJ                1394
#define IDC_OBJECT_ROBJ                 1395
#define IDC_OBJECT_IGRF                 1396
#define IDC_OBJECT_ICOLMAX              1397
#define IDC_OBJECT_ICOLMIN              1398
#define IDC_OBJECT_GRFH1                1399
#define IDC_OBJECT_GRFH2                1400
#define IDC_OBJECT_LMAT                 1401
#define IDC_OBJECT_LMATW0               1402
#define IDC_OBJECT_SPIRAL               1403
#define IDC_OBJECT_LFLG                 1404
#define IDC_OBJECT_IDRAOBJ              1405
#define IDC_OBJECT_LTRA                 1406
#define IDC_OBJECT_LDOM                 1407
#define IDC_MMP_UseRes                  1407
#define IDC_OBJECT_LFLD                 1408
#define IDC_OGL_XCOLOR                  1408
#define IDC_OGL_XLENGTH                 1409
#define IDC_EXPGEN2_KBND                1409
#define IDC_OBJECT_LEXP                 1409
#define IDC_OBJECT_LERR                 1410
#define IDC_OGL_XWIDTH                  1410
#define IDC_EXPGEN2_IDOM2               1410
#define IDC_OBJECT_LHID                 1411
#define IDC_OGL_YCOLOR                  1411
#define IDC_EXPGEN2_ICOL2               1411
#define IDC_OGL_YLENGTH                 1412
#define IDC_EXPGEN2_ICONN2              1412
#define IDC_OBJECT_TRIANGLE             1412
#define IDC_OGL_YWIDTH                  1413
#define IDC_OBJECT_SIOBJS               1413
#define IDC_EXPGEN2_NEXP                1413
#define IDC_OGL_ZCOLOR                  1414
#define IDC_OBJECT_SIOBJ                1414
#define IDC_OGL_ZLENGTH                 1415
#define IDC_EXPGEN2_NEXPBND             1415
#define IDC_OBJECT_RECTANGLE            1415
#define IDC_OGL_ZWIDTH                  1416
#define IDC_EXPGEN2_NSPL                1416
#define IDC_OBJECT_CONE                 1416
#define IDC_OBJECT_LDEF                 1417
#define IDC_OGL_XCOLOR2                 1417
#define IDC_EXPGEN2_IWF                 1417
#define IDC_OGL_IMOVIE                  1418
#define IDC_EXPGEN2_IWE                 1418
#define IDC_OGL_XWIDTH2                 1419
#define IDC_EXPGEN2_FMIN                1419
#define IDC_OGL_YCOLOR2                 1420
#define IDC_EXPGEN2_FMAX                1420
#define IDC_OGL_RMOVIE                  1421
#define IDC_EXPGEN2_FACT                1421
#define IDC_OGL_YWIDTH2                 1422
#define IDC_EXPGEN2_DELEXPCOL           1422
#define IDC_OGL_ZCOLOR2                 1423
#define IDC_EXPGEN2_DELEXPCON           1423
#define IDC_EXPGEN2_DFL                 1424
#define IDC_OGL_EXPLEN                  1424
#define IDC_OGL_ZWIDTH2                 1425
#define IDC_EXPGEN2_DLL                 1425
#define IDC_EXPGEN2_FINN                1426
#define IDC_EXPGEN2_DFR                 1427
#define IDC_OGL_XLOOKFROM               1427
#define IDC_EXPGEN2_DLR                 1428
#define IDC_OGL_VIEWANGLE               1428
#define IDC_EXPGEN2_FOUT                1429
#define IDC_OGL_YLOOKFROM               1429
#define IDC_EXPGEN2_GENEXP              1430
#define IDC_OGL_VIEWASPECT              1430
#define idc_ExpGen3_genExp              1431
#define IDC_OGL_ZLOOKFROM               1431
#define IDC_EXPGEN2_DINN                1431
#define IDC_OGL_XLOOKAT                 1432
#define IDC_MOBJECT_SETCOLOR            1432
#define IDC_EXPGEN2_AINN                1432
#define IDC_OGL_YLOOKAT                 1433
#define IDC_MOBJECT_COLOR               1433
#define IDC_OGL_ZLOOKAT                 1434
#define IDC_MOBJECT_SETCONN             1434
#define IDC_POINTS2D_TEXT               1434
#define IDC_EXPGEN2_DOUT                1434
#define IDC_OGL_WIDTH                   1435
#define IDC_MOBJECT_CONN                1435
#define IDC_POINTS2D_XA                 1435
#define IDC_EXPGEN2_AOUT                1435
#define IDC_OGL_HEIGHT                  1436
#define IDC_POINTS2D_YA                 1436
#define IDC_POINTS2D_XB                 1437
#define IDC_OGL_VIEWNEAR                1437
#define IDC_POINTS2D_YB                 1438
#define IDC_OGL_VIEWFAR                 1438
#define IDC_POINTS2D_XC                 1439
#define IDC_POINTS2D_YC                 1440
#define IDC_POINTS3D_ZA                 1441
#define IDC_POINTS3D_ZB                 1442
#define IDC_POINTS3D_ZC                 1443
#define IDC_POINTS3D_XA                 1444
#define IDC_POINTS3D_YA                 1445
#define IDC_POINTS3D_XB                 1446
#define IDC_POINTS3D_YB                 1447
#define IDC_POINTS3D_XC                 1448
#define IDC_POINTS3D_YC                 1449
#define idc_ExpMod2_Method1             1451
#define idc_ExpMod2_iExpMin             1452
#define idc_ExpMod2_iExpMax             1453
#define IDC_KTUBE                       1453
#define idc_ExpMod2_iBnd                1454
#define IDC_KTUBES                      1454
#define idc_ExpMod2_iDom                1455
#define IDC_NTUBE                       1455
#define idc_ExpMod2_Factor              1456
#define IDC_TUBECOLORo                  1456
#define idc_ExpMod2_iCol                1457
#define IDC_ADD_TUBE                    1457
#define idc_ExpMod2_iCon                1458
#define IDC_DEL_TUBE                    1458
#define idc_ExpMod2_iWFA                1459
#define IDC_TUBEX                       1459
#define idc_ExpMod2_Method2             1460
#define IDC_TUBEY                       1460
#define idc_ExpMod2_Method0             1461
#define IDC_TUBEZ                       1461
#define IDC_POINTS3D_TEXT               1461
#define idc_ExpMod2_iLoop               1462
#define IDC_TUBENR                      1462
#define IDC_PFD_nx                      1462
#define idc_ExpMod2_Method3             1463
#define IDC_TUBER                       1463
#define IDC_PFD_ny                      1463
#define idc_ExpMod2_Method4             1464
#define IDC_TUBED                       1464
#define IDC_PFD_nz                      1464
#define idc_ExpMod2_Method5             1465
#define IDC_TUBEND                      1465
#define IDC_PFD_xmin                    1465
#define idc_ExpMod2_Method6             1466
#define IDC_MODIFY_TUBE                 1466
#define IDC_PFD_iPFDs                   1466
#define idc_ExpMod2_Method7             1467
#define IDC_PFD_jPFDs                   1467
#define IDC_TUBECOLORi                  1467
#define idc_ExpMod2_iWFE                1468
#define IDC_PFD_xmax                    1468
#define IDC_TUBECOLORg                  1468
#define idc_ExpMod2_iObj                1469
#define IDC_PFD_dx                      1469
#define IDC_PFD_ymin                    1470
#define IDC_PFD_ymax                    1471
#define IDC_PFD_dy                      1472
#define IDC_PFD_zmin                    1473
#define IDC_PFD_zmax                    1474
#define IDC_PFD_dz                      1475
#define IDC_PFD_nLeft                   1476
#define IDC_PFD_kPFDs                   1477
#define IDC_PFD_nRight                  1478
#define IDC_PFD_nBottom                 1479
#define IDC_PFD_nTop                    1480
#define IDC_PFD_nBack                   1481
#define IDC_PFD_nFront                  1482
#define IDC_PFD_Decay                   1483
#define IDC_PFD_Tmax                    1484
#define IDC_PFD_Tau                     1485
#define IDC_PFD_hard                    1486
#define IDC_PFD_tExp                    1487
#define IDC_PFD_Soft                    1488
#define IDC_PFD_PFDsensX                1492
#define IDC_PFD_PFDsensY                1493
#define IDC_PFD_PFDsensZ                1494
#define IDC_PFD_nPFDf                   1495
#define IDC_PFD_fmin                    1496
#define IDC_PFD_tCos                    1497
#define IDC_PFD_tPulse                  1498
#define IDC_PFD_tRamp                   1499
#define IDC_PFD_Tharm                   1500
#define IDC_PFD_Hfield                  1501
#define IDC_PFD_Xcomp                   1502
#define IDC_PFD_Ycomp                   1503
#define IDC_PFD_Zcomp                   1504
#define IDC_PFD_fmax                    1505
#define IDC_PFD_SourceAr                1506
#define IDC_PFD_PFDsensT                1507
#define IDC_PFD_PFDsensD                1508
#define IDC_PFD_IEFF                    1509
#define IDC_PFD_nPFDsens                1510
#define IDC_PFD_kPFDsens                1511
#define IDC_PFD_ADD                     1512
#define IDC_PFD_DEL                     1513
#define IDC_PFD_MOD                     1514
#define IDC_PFD_kPFDsensS               1515
#define IDC_PFD_nPFDsource              1516
#define IDC_PFD_kPFDsource              1517
#define IDC_PFD_kPFDsourceS             1518
#define IDC_EXPGEN3_NODEL               1518
#define IDC_PFD_SourceAi                1519
#define IDC_PFD_ADDs                    1520
#define IDC_PFD_NSCATT                  1521
#define IDC_PFD_t0                      1522
#define IDC_PFD_DELs                    1523
#define IDC_PFD_MODs                    1524
#define IDC_PFD_Efield                  1525
#define IDC_READ_PFD                    1526
#define IDC_WRITE_PFD                   1527
#define IDC_APPLY_PFD                   1528
#define IDC_PFD_N                       1529
#define IDC_PFD_lPW                     1530
#define IDC_PFD_lP                      1531
#define IDC_PFD_lMMP                    1532
#define IDC_PFD_DT                      1533
#define IDC_GEO_BND1                    1534
#define IDC_GEO_BND2                    1535
#define IDC_GEO_DOM                     1536
#define IDC_GEO_COL                     1537
#define IDC_WRITE_GEO                   1538

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        264
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1539
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
